// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Function_Generator

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Index
void ui_Index_screen_init(void);
lv_obj_t *ui_Index;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_sine_wave_btn;
lv_obj_t *ui_Label3;
lv_obj_t *ui_square_wave_btn;
lv_obj_t *ui_Label1;
lv_obj_t *ui_triangle_wave_btn;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_freq_input;
lv_obj_t *ui_unit_hz_btn;
lv_obj_t *ui_Label6;
lv_obj_t *ui_unit_khz_btn;
lv_obj_t *ui_Label7;
lv_obj_t *ui_unit_mhz_btn;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_amplitude_input;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_offset_input;
lv_obj_t *ui_Label10;
lv_obj_t *ui_output_btn;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_wave_form_img;
lv_obj_t *ui_Label14;
lv_obj_t *ui_output_log_label;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Index_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Index);
}
