// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Function_Generator

#ifndef _FUNCTION_GENERATOR_UI_H
#define _FUNCTION_GENERATOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t *ui_Index;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_wave_form_img;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_output_log_label;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_sine_wave_btn;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_square_wave_btn;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_triangle_wave_btn;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_freq_input;
extern lv_obj_t *ui_unit_hz_btn;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_unit_khz_btn;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_unit_mhz_btn;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_amplitude_input;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_offset_input;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_output_btn;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_keypad;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_sine_png);   // assets\sine.png
LV_IMG_DECLARE( ui_img_square_png);   // assets\square.png
LV_IMG_DECLARE( ui_img_tri_png);   // assets\tri.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
